export const dummy ={
                "item": [
                    {
                        "actbegintm": 6,
                        "actendtm": 23,
                        "actplace": "구글 링크 주소 : https://forms.gle/8wjayJDzb5ACy5MG6",
                        "adultposblat": "Y",
                        "guguncd": 3500000,
                        "nanmmbynm": "동구자원봉사센터",
                        "noticebgnde": 20231024,
                        "noticeendde": 20231231,
                        "progrmbgnde": 20231024,
                        "progrmendde": 20231231,
                        "progrmregistno": 3052711,
                        "progrmsj": "[필독] 인천동구자원봉사센터 소속봉사자 - 휴면 봉사자를 위한 자원봉사자 보수교육(비대면 봉사학습)",
                        "progrmsttusse": 2,
                        "sidocd": 6280000,
                        "srvcclcode": "자원봉사교육 ",
                        "url": "https://1365.go.kr/vols/P9210/partcptn/timeCptn.do?type=show&progrmRegistNo=3052711",
                        "yngbgsposblat": "Y"
                    },
                    {
                        "actbegintm": 18,
                        "actendtm": 19,
                        "actplace": "참가자 자택(온라인 참여)",
                        "adultposblat": "N",
                        "guguncd": 3100000,
                        "nanmmbynm": "서울특별시 노원구",
                        "noticebgnde": 20231011,
                        "noticeendde": 20231225,
                        "progrmbgnde": 20231011,
                        "progrmendde": 20231225,
                        "progrmregistno": 3046211,
                        "progrmsj": "[노원구자원봉사센터] 4분기 자원봉사교육 및 활성화 캠페인",
                        "progrmsttusse": 2,
                        "sidocd": 6110000,
                        "srvcclcode": "자원봉사교육 ",
                        "url": "https://1365.go.kr/vols/P9210/partcptn/timeCptn.do?type=show&progrmRegistNo=3046211",
                        "yngbgsposblat": "Y"
                    },
                    {
                        "actbegintm": 9,
                        "actendtm": 10,
                        "actplace": "보령시자원봉사센터 2층 (보령북로 75)",
                        "adultposblat": "Y",
                        "guguncd": 4510000,
                        "nanmmbynm": "충청남도 보령시",
                        "noticebgnde": 20231005,
                        "noticeendde": 20240104,
                        "progrmbgnde": 20231005,
                        "progrmendde": 20240104,
                        "progrmregistno": 3043972,
                        "progrmsj": "한땀한땀 전문봉사단(바느질) 모집",
                        "progrmsttusse": 2,
                        "sidocd": 6440000,
                        "srvcclcode": "자원봉사교육 ",
                        "url": "https://1365.go.kr/vols/P9210/partcptn/timeCptn.do?type=show&progrmRegistNo=3043972",
                        "yngbgsposblat": "Y"
                    },
                    {
                        "actbegintm": 18,
                        "actendtm": 20,
                        "actplace": "유튜브(https://youtu.be/dmbVmldg2GQ)",
                        "adultposblat": "Y",
                        "guguncd": 3520000,
                        "nanmmbynm": "연수구자원봉사센터",
                        "noticebgnde": 20231018,
                        "noticeendde": 20231201,
                        "progrmbgnde": 20231019,
                        "progrmendde": 20231208,
                        "progrmregistno": 3049914,
                        "progrmsj": "(비대면/온라인교육 및 캠페인) 그린상륙작전V-(슬)기로운.(기)후.(생)활_ 그린숲",
                        "progrmsttusse": 2,
                        "sidocd": 6280000,
                        "srvcclcode": "자원봉사교육 ",
                        "url": "https://1365.go.kr/vols/P9210/partcptn/timeCptn.do?type=show&progrmRegistNo=3049914",
                        "yngbgsposblat": "Y"
                    },
                    {
                        "actbegintm": 18,
                        "actendtm": 20,
                        "actplace": "연수구자원봉사센터 유튜브(https://youtu.be/IHr2oRh0ZbU)",
                        "adultposblat": "Y",
                        "guguncd": 3520000,
                        "nanmmbynm": "연수구자원봉사센터",
                        "noticebgnde": 20231102,
                        "noticeendde": 20231201,
                        "progrmbgnde": 20231102,
                        "progrmendde": 20231210,
                        "progrmregistno": 3057036,
                        "progrmsj": "(비대면/온라인) 그린상륙작전V-(슬)기로운.(기)후.(생)활_탄소는 Bye,그린은 Buy",
                        "progrmsttusse": 2,
                        "sidocd": 6280000,
                        "srvcclcode": "자원봉사교육 ",
                        "url": "https://1365.go.kr/vols/P9210/partcptn/timeCptn.do?type=show&progrmRegistNo=3057036",
                        "yngbgsposblat": "Y"
                    }
                ],
                "numofrows": 5,
            "pageno": 1,
            "totalcount": 7987
            }
            